dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- mvn clean test
- sonar-scanner
addons:
  sonarcloud:
    organization: bazhanel-github
    token: 6fe2c756e6e564790a4e82f78fc13824ee86f6d5
